name: Deploy github pages

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build docs
      run: |
        wget -q https://github.com/gohugoio/hugo/releases/download/v0.92.1/hugo_0.92.1_Linux-64bit.tar.gz
        tar xf hugo_0.92.1_Linux-64bit.tar.gz 
        ./hugo

    - name: Publish docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        wget -q https://github.com/dbradf/gh-pages-publish/releases/download/0.2.0/gh-pages-publish-linux
        chmod +x gh-pages-publish-linux
        git remote set-url --push origin https://dbradf:$GITHUB_TOKEN@github.com/dbradf/dbradf.github.io
        ./gh-pages-publish-linux --docs-dir public --verbose
